version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: ''
    volumes:
      - pihole_config:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
      - pihole_logs:/var/log/
    dns:
      - 127.0.0.1
      - 8.8.8.8
    restart: unless-stopped

volumes:
  pihole_config:
  pihole_dnsmasq:
  pihole_logs:
