services:
  pihole:
    container_name: pihole
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PIHOLE_VERSION=${PIHOLE_VERSION:-latest}
    ports:
      - "${DNS_PORT:-53}:53/tcp"
      - "${DNS_PORT:-53}:53/udp"
      - "8080:443/tcp"
    environment:
      TZ: 'Europe/Madrid'
      FTLCONF_webserver_api_password: ${WEBPASSWORD:-12345Abcde}
    volumes:
      - pihole_config:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
      - pihole_logs:/var/log/
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped

volumes:
  pihole_config:
  pihole_dnsmasq:
  pihole_logs:
