services:
  pihole:
    container_name: pihole
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PIHOLE_VERSION=${PIHOLE_VERSION:-latest}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - pihole_config:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
      - pihole_logs:/var/log/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped

volumes:
  pihole_config:
  pihole_dnsmasq:
  pihole_logs:
